export default {
    FETCH_TRADE_TOKEN_LIST: "FETCH_TRADE_TOKEN_LIST",
    FETCH_LANGUAGE_LIST: "FETCH_LANGUAGE_LIST",
    FETCH_SMART_CONTRACT: "FETCH_SMART_CONTRACT",
    FETCH_TOKEN_LIST: "FETCH_TOKEN_LIST",
    FETCH_VOLUME_LIST: "FETCH_VOLUME_LIST",
    FETCH_PRICE_CHART_DATA: "FETCH_PRICE_CHART_DATA",
    FETCH_DEPTH_CHART_DATA: "FETCH_DEPTH_CHART_DATA",
    FETCH_TRADE_DATA: "FETCH_TRADE_DATA",
    FETCH_ORDER_DATA: "FETCH_ORDER_DATA",
    FETCH_FUND_DATA: "FETCH_FUND_DATA",
    FETCH_TRADE_LIST: "FETCH_TRADE_LIST"
}