export default {
    FETCH_TRADE_TOKEN_LIST: "FETCH_TRADE_TOKEN_LIST",
    FETCH_LANGUAGE_LIST: "FETCH_LANGUAGE_LIST",
    FETCH_SMART_CONTRACT: "FETCH_SMART_CONTRACT",
    FETCH_TOKEN_LIST: "FETCH_TOKEN_LIST",

}